customhost = "employee.ckmztvxuasgp.ap-southeast-1.rds.amazonaws.com"
customuser = "admin"
custompass = "12345678"
customdb = "employee"
custombucket = "dynamicweb121"
customregion = "ap-southeast-1"
